spring:
  application:
    name: service-feign
server:
  port: 8084
eureka:
  client:
    service-url:
     defaultZone: http://localhost:8081/eureka/
  instance:
    hostname: localhost
feign:
  hystrix:
    enabled: true