spring:
  application:
    name: service-zuul
server:
  port: 8085
eureka:
  client:
    service-url:
     defaultZone: http://localhost:8081/eureka/
  instance:
    hostname: localhost
zuul:
  routes:
    api-a:
     path: /api-a/**
     serviceId: service-ribbon
    api-b:
     path: /api-b/**
     serviceId: service-feign